[package]
name = "jtd_codegen"
version = "0.1.0"
authors = ["Ulysse Carion <ulysse@segment.com>"]
edition = "2018"

[dependencies]
thiserror = "1.0.22"
teeter_inflector = { version = "0.11.4", package = "Inflector" }
jtd = "0.2.1"
serde_json = "1.0"
